### ISSUE TITLE
Calculate 1 percentile lows for VMAF

### ISSUE THREAD

**Issue by samtheruby1012** [alexheretic/ab-av1#164]
First I just wanted to thank you for this amazing project, it's a integral part of my workflow when I encode anything.

I wanted to know if there would be a way to make the program also take into account the 1 percentile lows when it's calculating VMAF as there are times when I'll use the suggested CRF and while it will work for most of the encode, I'll end up having some really low spikes in VMAF, sometimes below a score of 80. Is there any way to make the code also take 1 percentile lows for VMAF into account?

Thank you for all your work and hopefully for a reply!

P.S. I'd gladly donate for this feature to be added BTW.

**Comment by t-nil** [comment]
Hey,

maybe using a different pooling method can solve your problem. [^1] [^2] You can use it with `--vmaf pool=harmonic_mean`. Be advised though that due to an upstream bug `harmonic_mean` only works when you build FFmpeg from Git (hopefully it's fixed in the next release).

[^1]: https://netflixtechblog.com/vmaf-the-journey-continues-44b51ee9ed12
[^2]: https://ffmpeg.org/ffmpeg-filters.html#libvmaf-1 , see `pool`

**Comment by alexheretic** [comment]
Yep using the harmonic mean meets a similar use case.

An issue with both is that while taking samples and averaging them is a decent approximation of the overall average, doing the same with harmonic/quantiles seems more flawed. I imagine it's much more likely an unsampled part of the video would have a significant effect on the score.

This can already be mitigated by using more samples / doing full pass.

While we can already opt for harmonic mean (ffmpeg willing) ab-av1 will still average the sample scores together. Maybe it makes sense to calculate a _harmonic_ mean of each sample's harmonic mean in this case.

**Comment by SamTheRuby** [comment]
> Hey,
> 
> maybe using a different pooling method can solve your problem. [1](#user-content-fn-1-91a44591f7991d121ba5ab7bf5bc20a7) [2](#user-content-fn-2-91a44591f7991d121ba5ab7bf5bc20a7) You can use it with `--vmaf pool=harmonic_mean`. Be advised though that due to an upstream bug `harmonic_mean` only works when you build FFmpeg from Git (hopefully it's fixed in the next release).
> 
> Also, VMAF params don't get incorporated into the hash for the cache, so if you want to force recalculation, add a `:` to the vfilter param list (e.g.) or simply delete the cache. I am working on a PR right now.
> 
> ## Footnotes
> 1. https://netflixtechblog.com/vmaf-the-journey-continues-44b51ee9ed12 [↩](#user-content-fnref-1-91a44591f7991d121ba5ab7bf5bc20a7)
> 2. https://ffmpeg.org/ffmpeg-filters.html#libvmaf-1 , see `pool` [↩](#user-content-fnref-2-91a44591f7991d121ba5ab7bf5bc20a7)

Can I use the build at [](https://www.gyan.dev/ffmpeg/builds/) specifically 
![Screenshot 2023-12-29 113541](https://github.com/alexheretic/ab-av1/assets/53793412/c33ddeaf-c538-41f0-a5a9-6e952d955d61)

Is that version recent enough to contain the VMAF fix?

**Comment by SamTheRuby** [comment]
> Yep using the harmonic mean meets a similar use case.
> 
> An issue with both is that while taking samples and averaging them is a decent approximation of the overall average, doing the same with harmonic/quantiles seems more flawed. I imagine it's much more likely an unsampled part of the video would have a significant effect on the score.
> 
> This can already be mitigated by using more samples / doing full pass.
> 
> While we can already opt for harmonic mean (ffmpeg willing) ab-av1 will still average the sample scores together. Maybe it makes sense to calculate a _harmonic_ mean of each sample's harmonic mean in this case.

I already use 1 sample per minute but still have the issue, what do you mean "calculate a _harmonic_ mean of each sample's harmonic mean in this case", how would I do that?

**Comment by alexheretic** [comment]
> what do you mean "calculate a _harmonic_ mean of each sample's harmonic mean in this case", how would I do that?

It is something we'd need to add to ab-av1 code to detect when harmonic mean is being used and aggregate the sample scores appropriately.

**Comment by SamTheRuby** [comment]
Is it possible to add that?

**Comment by alexheretic** [comment]
Yes seems doable 🙂

**Comment by SamTheRuby** [comment]
That would be great, and if it can aalso display 1 percent lows for VMAF, that would be even better!

**Comment by t-nil** [comment]
> > Hey,
> > maybe using a different pooling method can solve your problem. [1](#user-content-fn-1-91a44591f7991d121ba5ab7bf5bc20a7) [2](#user-content-fn-2-91a44591f7991d121ba5ab7bf5bc20a7) You can use it with `--vmaf pool=harmonic_mean`. Be advised though that due to an upstream bug `harmonic_mean` only works when you build FFmpeg from Git (hopefully it's fixed in the next release).
> > Also, VMAF params don't get incorporated into the hash for the cache, so if you want to force recalculation, add a `:` to the vfilter param list (e.g.) or simply delete the cache. I am working on a PR right now.
> > ## Footnotes
> > 
> > 1. https://netflixtechblog.com/vmaf-the-journey-continues-44b51ee9ed12 [↩](#user-content-fnref-1-91a44591f7991d121ba5ab7bf5bc20a7)
> > 2. https://ffmpeg.org/ffmpeg-filters.html#libvmaf-1 , see `pool` [↩](#user-content-fnref-2-91a44591f7991d121ba5ab7bf5bc20a7)
> 
> Can I use the build at specifically ![Screenshot 2023-12-29 113541](https://private-user-images.githubusercontent.com/53793412/293396922-c33ddeaf-c538-41f0-a5a9-6e952d955d61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzY3NzIsIm5iZiI6MTcwMzkzNjQ3MiwicGF0aCI6Ii81Mzc5MzQxMi8yOTMzOTY5MjItYzMzZGRlYWYtYzUzOC00MWYwLWE1YTktNmU5NTJkOTU1ZDYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDExNDExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMjk0NDg3NmIzNmY1MTg2MmIzNzYzZjRkYzZhYzUyZWY2ZmM5MDUzYTRiNDkyZTJmNzEzNmQyOTQ5MjRhZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J3ZMH6Bq7LMqK1xiRPg05XsxzCIPrjkPCrZ3dThnSfw)
> 
> Is that version recent enough to contain the VMAF fix?

I strongly assume yes. You can check: run `ab-av1 vmaf [...] --vmaf pool=harmonic_mean` and vanilla `ab-av1 vmaf [...]`. If the build is faulty, both numbers will be exactly the same in every video.

**Comment by SamTheRuby** [comment]
thanks @t-nil for getting the ball rolling on a potential fix! 🙂

**Comment by stephen304** [comment]
So I'm not really a math person but I was curious what it would look like to combine the harmonic means (and how that works) and I came across the [formula from here](https://www.vedantu.com/question-answer/if-there-are-two-groups-with-75-and-65-as-class-11-maths-cbse-6148b984c98a9e3cd98bbe09), and if the sample size of each individual harmonic mean is the same (which seems like is usually the case for ab-ab1?) it looks like it simplifies to:

n/ ((1/x1) + (1/x2))

It looks like it's essentially just the harmonic mean of the other harmonic means, and I did a few tests with random numbers and it looks like this is basically the same as the harmonic mean of all the samples combined:

| Real harmonic mean (all samples together) | Group A (first half of samples harmonic mean) | Group B | Harmonic of a+b | AVG of a+b harmonic |
| --- | --- | --- | --- | --- |
| 93.3730 | 91.8138 | 94.9861 | 93.3730 | 93.4000 |
| 93.8652 | 92.1357 | 95.6609 | 93.8652 | 93.8983 |

I've never written any rust before but I managed to put this together this patch which seems to work:

```diff
diff --git a/src/command/sample_encode.rs b/src/command/sample_encode.rs
index 91a37dc..1c627e6 100644
--- a/src/command/sample_encode.rs
+++ b/src/command/sample_encode.rs
@@ -429,9 +429,19 @@ pub fn run(
             yield Update::SampleResult { sample: sample_n, result };
         }

+        let score = match &scoring {
+            ScoringInfo::Vmaf(vmaf, _) => {
+                if vmaf.vmaf_args.iter().any(|arg| arg.starts_with("pool=harmonic_mean")) {
+                    results.harmonic_mean_score()
+                } else {
+                    results.mean_score()
+                }
+            }
+            _ => results.mean_score(),
+        };
         let score_kind = results.score_kind();
         let output = Output {
-            score: results.mean_score(),
+            score,
             score_kind,
             // Using file size * encode_percent can over-estimate. However, if it ends up less
             // than the duration estimation it may turn out to be more accurate.
@@ -576,6 +586,8 @@ trait EncodeResults {

     fn mean_score(&self) -> f32;

+    fn harmonic_mean_score(&self) -> f32;
+
     /// Return estimated encoded **video stream** size by multiplying sample size by duration.
     fn estimate_encode_size_by_duration(
         &self,
@@ -608,6 +620,15 @@ impl EncodeResults for Vec<EncodeResult> {
         self.iter().map(|r| r.score).sum::<f32>() / self.len() as f32
     }

+    fn harmonic_mean_score(&self) -> f32 {
+        if self.is_empty() {
+            return 0.0;
+        }
+        let n = self.len() as f32;
+        let sum_reciprocal = self.iter().map(|r| 1.0 / r.score).sum::<f32>();
+        n / sum_reciprocal
+    }
+
     fn estimate_encode_size_by_duration(
         &self,
         input_duration: Duration,
```

Maybe the arg parsing could be refactored a little higher but I was just itching to try this out for some encodes and thought I'd share
