### ISSUE TITLE
VMAF inconsistency with .m2ts files

### ISSUE THREAD

**Issue by iPaulis** [alexheretic/ab-av1#70]
Following the latest posts in #63, there seem to be some inconsistencies in the vmaf results of .m2ts files.
Testing ongoing.

**Comment by iPaulis** [comment]
Here are some sample video files (AVC h264) in several bitrates and in both .m2ts and .mkv containers.
https://dl.ganjanetwork.ru/Files/Video%20Test%20Files/Bitrate/Birds/

I tested a couple of them to see the vmaf inconsistencies between m2ts and mkv. It is also possible to change a m2ts container into mkv with MKVToolNix, and the results should be similar and reproducible.

- Default av1 .m2ts file:
`ab-av1 crf-search --min-vmaf 89 --vmaf pool=harmonic_mean --vmaf n_threads=16 -i .\bird50.m2ts --preset 6`
> - crf 32 VMAF 98.40 (53%)
> - crf 43 VMAF 89.83 (23%)
> - crf 55 VMAF 68.45 (9%)
> - crf 44 VMAF 88.21 (22%)
> crf 43 VMAF 89.83 predicted full encode size 32.59 MiB (23%) taking 49 seconds

It does not seem that bad, right? but when we check the same video in the mkv container:
`ab-av1 crf-search --min-vmaf 89 --vmaf pool=harmonic_mean --vmaf n_threads=16 -i .\bird50.mkv --preset 6`
> - crf 32 VMAF 99.94 (57%)
> - crf 43 VMAF 96.13 (27%)
> - crf 55 VMAF 75.16 (11%)
> - crf 47 VMAF 91.08 (20%)
> crf 48 VMAF 89.39 predicted full encode size 25.25 MiB (19%) taking 72 seconds

Then we can see that there is a noticeable difference in the vmaf results, even using the av1 encoder, when they should be pretty similar for the same video file.

When trying the x265 encoder the differences are even higher:
`ab-av1 crf-search -e libx265 --min-vmaf 81 --vmaf pool=harmonic_mean --vmaf n_threads=16 -i .\bird50.m2ts --preset slow`
> - crf 32 VMAF 82.44 (21%)
> - crf 43 VMAF 36.10 (3%)
> - crf 33 VMAF 78.91 (18%)
> crf 32 VMAF 82.44 predicted full encode size 29.07 MiB (21%) taking 30 seconds
--------------------------------------------------------------------------------------------------
`ab-av1 crf-search -e libx265 --min-vmaf 81 --vmaf pool=harmonic_mean --vmaf n_threads=16 -i .\bird50.mkv --preset slow`
> - crf 32 VMAF 90.20 (22%)
> - crf 43 VMAF 43.36 (4%)
> - crf 34 VMAF 83.42 (17%)
> - crf 35 VMAF 79.47 (15%)
> crf 34 VMAF 83.42 predicted full encode size 22.47 MiB (17%) taking 54 seconds

Again, the results are inconsistent, and the same thing happens with other sample files with both av1 and x265 encoders.
It is a pitty, because all blurays come in m2ts container, so it's a quite common source video filetype.

**Comment by alexheretic** [comment]
Thanks for the info. I'll try to reproduce myself.

As i said before it probably makes sense to default output to something like .mp4 in this case & I wonder if that would improve things on it's own. I'll do some testing.

**Comment by alexheretic** [comment]
The linked bird examples are very short and the method of creating a 20s sample seems less effective for .m2ts than for .mp4 or .mkv. I think this is why the VMAF results are different, because the samples are different.

If I test with `--samples 3` it'll use the entire video as a sample, as it's under 60s, in this case the results seem consistent across the container formats.

**svt-av1**
```
$ ab-av1 sample-encode -i bird50.m2ts --crf 40 --samples 3
VMAF 93.28 predicted full encode size 42.08 MiB (30%) taking 36 seconds         
                                        
$ ab-av1 sample-encode -i bird50.m2ts.mp4 --crf 40 --samples 3
VMAF 93.28 predicted full encode size 42.08 MiB (31%) taking 36 seconds
```

**x265**
```
$ ab-av1 sample-encode -i bird50.m2ts --crf 25 --samples 3 -e libx265
VMAF 97.41 predicted full encode size 67.45 MiB (48%) taking 30 seconds

$ ab-av1 sample-encode -i bird50.m2ts.mp4 --crf 25 --samples 3 -e libx265
VMAF 97.41 predicted full encode size 64.50 MiB (48%) taking 30 seconds
```

Thoughts:
* We could try a slower method to create samples for m2ts. I'm not sure it's worth it though, as shorter samples should still give a decent result taken across a larger video. And samples don't have to be stable across different containers, they just need to approximate the end VMAF result.
* When the sample total is quite close to the actual full video time (like 20s vs 22s here) we should default to full-encode sampling (like we already do when the sample total _exceeds_ the full time). Perhaps when the sample time is 80 or 90%?
* av1.m2ts doesn't work, I don't think the container can support it. The sampling works as we don't use that format. I think we should start defaulting the output format to .mp4 or .mkv instead of using the input format.

**Comment by alexheretic** [comment]
I've created #71 & #72

**Comment by iPaulis** [comment]
Apart from those 2 points, I think something else is still going on with m2ts files.
I understand that those sample files are too small/short to test properly, but the first [results I got yesterday](https://github.com/alexheretic/ab-av1/issues/63#issuecomment-1325747975) were with a full bluray movie with a duration over 2h, and I also tested it changing the m2ts container into mkv, and got different vmaf results only with x265, while av1 remained the same.

So for the same video file:
m2ts crf-search with av1 --> OK
mkv crf-search with av1 --> OK, similar results as expected

m2ts crf-search with x265 --> KO, disastrous vmaf results that don't make sense
mkv crf-search with x265 --> OK, reasonable vmaf results that make sense

What could be the explanation for this inconsistency between container formats?

Here is the mediainfo of the video in both containers:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD></HEAD>
<BODY><TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY>
<TR>
<TD width=150>
<H2>M2TS Vídeo</H2></TD></TR>
<TR>
<TD><I>ID :</I></TD>
<TD colSpan=3>4113 (0x1011)</TD></TR>
<TR>
<TD><I>ID menú :</I></TD>
<TD colSpan=3>1 (0x1)</TD></TR>
<TR>
<TD><I>Formato :</I></TD>
<TD colSpan=3>VC-1</TD></TR>
<TR>
<TD><I>Formato del perfil :</I></TD>
<TD colSpan=3>Advanced@L3</TD></TR>
<TR>
<TD><I>ID códec :</I></TD>
<TD colSpan=3>234</TD></TR>
<TR>
<TD><I>Duración :</I></TD>
<TD colSpan=3>2 h 21 min</TD></TR>
<TR>
<TD><I>Ancho :</I></TD>
<TD colSpan=3>1 920 píxeles</TD></TR>
<TR>
<TD><I>Alto :</I></TD>
<TD colSpan=3>1 080 píxeles</TD></TR>
<TR>
<TD><I>Relación de aspecto :</I></TD>
<TD colSpan=3>16:9</TD></TR>
<TR>
<TD><I>Velocidad de fotogramas :</I></TD>
<TD colSpan=3>23,976 (24000/1001) FPS</TD></TR>
<TR>
<TD><I>Espacio de color :</I></TD>
<TD colSpan=3>YUV</TD></TR>
<TR>
<TD><I>Submuestreo croma :</I></TD>
<TD colSpan=3>4:2:0</TD></TR>
<TR>
<TD><I>Profundidad bits :</I></TD>
<TD colSpan=3>8 bits</TD></TR>
<TR>
<TD><I>Tipo barrido :</I></TD>
<TD colSpan=3>Progresivo</TD></TR>
<TR>
<TD><I>Modo de compresión :</I></TD>
<TD colSpan=3>Con pérdida</TD></TR></TBODY></TABLE></BODY></HTML>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD></HEAD>
<BODY>
<TABLE 
style="BORDER-TOP: navy 1px solid; BORDER-RIGHT: navy 1px solid; BORDER-BOTTOM: navy 1px solid; BORDER-LEFT: navy 1px solid" 
cellSpacing=2 cellPadding=1 width="100%" border=0>
<TBODY><TR>
<TD width=150>
<H2>MKV Vídeo</H2></TD></TR>
<TR>
<TD><I>ID :</I></TD>
<TD colSpan=3>1</TD></TR>
<TR>
<TD><I>Formato :</I></TD>
<TD colSpan=3>VC-1</TD></TR>
<TR>
<TD><I>Formato del perfil :</I></TD>
<TD colSpan=3>Advanced@L3</TD></TR>
<TR>
<TD><I>ID códec :</I></TD>
<TD colSpan=3>V_MS/VFW/FOURCC / WVC1</TD></TR>
<TR>
<TD><I>ID códec/Consejo :</I></TD>
<TD colSpan=3>Microsoft</TD></TR>
<TR>
<TD><I>Duración :</I></TD>
<TD colSpan=3>2 h 21 min</TD></TR>
<TR>
<TD><I>Tasa de bits :</I></TD>
<TD colSpan=3>19,3 Mb/s</TD></TR>
<TR>
<TD><I>Ancho :</I></TD>
<TD colSpan=3>1 920 píxeles</TD></TR>
<TR>
<TD><I>Alto :</I></TD>
<TD colSpan=3>1 080 píxeles</TD></TR>
<TR>
<TD><I>Relación de aspecto :</I></TD>
<TD colSpan=3>16:9</TD></TR>
<TR>
<TD><I>Modo velocidad fotogramas :</I></TD>
<TD colSpan=3>Constante</TD></TR>
<TR>
<TD><I>Velocidad de fotogramas :</I></TD>
<TD colSpan=3>23,976 (24000/1001) FPS</TD></TR>
<TR>
<TD><I>Espacio de color :</I></TD>
<TD colSpan=3>YUV</TD></TR>
<TR>
<TD><I>Submuestreo croma :</I></TD>
<TD colSpan=3>4:2:0</TD></TR>
<TR>
<TD><I>Profundidad bits :</I></TD>
<TD colSpan=3>8 bits</TD></TR>
<TR>
<TD><I>Tipo barrido :</I></TD>
<TD colSpan=3>Progresivo</TD></TR>
<TR>
<TD><I>Modo de compresión :</I></TD>
<TD colSpan=3>Con pérdida</TD></TR>
<TR>
<TD><I>Bits/(píxel*fotograma) :</I></TD>
<TD colSpan=3>0.388</TD></TR>
<TR>
<TD><I>Tamaño de pista :</I></TD>
<TD colSpan=3>19,1 GiB (70%)</TD></TR>
<TR>
<TD><I>Default :</I></TD>
<TD colSpan=3>Sí</TD></TR>
<TR>
<TD><I>Forced :</I></TD>
<TD colSpan=3>No</TD></TR></TBODY></TABLE></BODY></HTML>

**Comment by alexheretic** [comment]
I don't think x265 really works well with m2ts output. Previously ffmpeg encoders would use the input extension for the encoded sample files, i.e. m2ts (svt-av1 samples are always the same ext so aren't affected).

With #74 it'll use mkv encoded samples instead, so should fix this issue.

**Comment by iPaulis** [comment]
Yes, I was just realizing how that works testing that movie file again.
Sample splits are always created with the same source .m2ts extension, but then, when being encoded, av1 is using .ivf extension files, but x265 still maintains .m2ts extension, which seems the origin of the discrepancy, as you were explaining.

**Comment by iPaulis** [comment]
I compiled the new version and I'm still getting the same inaccurate vmaf results. 
Now I see that the sample splits are converted into mkv when they are encoded with x265, but it does not seem to have any effect at all in the vmaf values, they are exactly the [same as yesterday](https://github.com/alexheretic/ab-av1/issues/63#issuecomment-1325747975).
No idea why.

**Comment by iPaulis** [comment]
OK, I got a clue and I've been narrowing down the options, so I think I have a theory of what is happening.

First of, here is a retest of the bluray movie in m2ts and mkv containers with the latest ab-av1 build. 
This time I tried x265 10bit medium:

```
ab-av1 crf-search -e libx265 --pix-format yuv420p10le --min-vmaf 90 --vmaf pool=harmonic_mean --vmaf n_threads=16 -i 
.\00163.m2ts --preset 5
```
> - crf 32 VMAF 49.53 (3%, 926.62 MiB) in 71 minutes
> - crf 21 VMAF 52.84 (17%, 5.03 GiB) in 2 hours
> - crf 10 VMAF 53.22 (116%, 33.95 GiB) in 3 hours
--------------------------------------------------------------------------------------------------
```
ab-av1 crf-search -e libx265 --pix-format yuv420p10le --min-vmaf 90 --vmaf pool=harmonic_mean --vmaf n_threads=16 -i 
.\00163.mkv --preset 5
```
> - crf 32 VMAF 83.03 (3%, 875.66 MiB) in 69 minutes
> - crf 21 VMAF 95.28 (18%, 4.85 GiB) in 2 hours
> - crf 26 VMAF 91.73 (7%, 2.02 GiB) in 2 hours
> crf 27 VMAF 90.69 predicted full encode size 1.73 GiB (6%) taking 2 hours

The m2ts vmaf results are horrible and don't make much sense for such high crf. Meanwhile, the mkv vmaf results seem to be fine with the same x265 encoder, and the expected result would be to get fairly similar vmaf results regardless of the container.
In this latest version, ab-av1 is indeed outputting the encoded samples in mkv instead of the source m2ts, but it does not help.

The reason seems to be that the first few frames of each encoded sample is full of artifacts that destroy the image and damage the vmaf calculation. The source m2ts split samples are fine, it is the x265 encoded ones that are corrupt in the first 15-20 frames.
I checked if this happened when the source file and samples were in mkv and it didn't; all those samples and encoded samples were perfectly fine.
I also checked that the same problem was happening yesterday, before the latest changes to ab-av1, and that is exactly what was happening. The previous version was outputting the encoded samples in the same source container, and the artifacts were there, in the first frames of each encoded sample.

So it is not exactly an issue with the m2ts container, I believe it is an issue with x265 encoding the m2ts sample resulting in a corrupted video file in the first frames. I could upload some of those corrupted samples here to show you, but they are parts of a bluray movie, so I'm not sure if that is ok.

That would explain the lower vmaf scores (big difference in a long video file), and it also explains why yesterday the small/short test files we downloaded to reproduce this issue were being inconsistent only by a little margin, because they were short clips and there was only one sample being encoded. In this new version of ab-av1 those results seem consistent now, because they are not being sampled at all, so no splitting, no encoding split sample file, no corrupted frames.

**Comment by iPaulis** [comment]
Here is an idea that could fix this, I hope it makes sense.

Now crf-search splits the source file into samples maintaining the source container, in this case m2ts, then goes encoding all those samples one by one in x265 and changes the output container into mkv, resulting in corrupted frames. The problem originates in this last step.

I suggest to change the order. 

First split the source file into samples, but do not maintain the source m2ts container, change it into mkv in this step. Then continue as usual, encoding the sample files without needing to change containers anymore.

This would be a workflow equivalent to changing the container thought MKVToolNix manually and then running ab-av1 (that splits video in samples, encodes them, and so on...), which I already tried and know it works (see vmaf results above), so I believe this workflow change should fix this and any other similar issue between containers vs encoders.

This way the sample files to encode in crf-search will always be in mkv/mp4 and they would be less likely to fail, as there would be a lower combination of containers and encoders having to work well with each other, only the 2 most compatible ones that we already know support most of the encoders. It's like standardising the process, making it more universal to avoid having to worry about container/encoder mismatches anymore.

What do you think? is it viable?

PS: sorry for my English, it's not my first language, I hope I'm making myself understood in general, it has not been easy trying to explain all those things clearly. And thank you again for this great tool and for keeping improving it.

**Comment by alexheretic** [comment]
> First split the source file into samples, but do not maintain the source m2ts container, change it into mkv in this step. 

Yeah it could work, ffmpeg can losslessly convert to mkv container in many cases. So perhaps the same extension logic will work for the lossless samples too? I'll need to give it a test, but in a lot of cases when the input is mp4/mkv anyway nothing will have changed. So probably not a huge risk changing it.

**Comment by alexheretic** [comment]
@iPaulis can you try #78 and see if everything looks ok?

**Comment by iPaulis** [comment]
In a few words, the fix works perfectly. 
There is a huge improvement to the vmaf scores and now all vmaf results are consistent between containers and encoders. Overall, it seems that using mkv for the lossless samples makes the process more robust and accurate.

I tested it with 2 full bluray movies, both in m2ts and manually converted into mkv.
**File 1, old branch:**
`ab-av1 crf-search -e libx265 --pix-format yuv420p10le --min-vmaf 90 --vmaf pool=harmonic_mean --vmaf n_threads=16 -i .\00004.m2ts --preset 5`
> - crf 32 VMAF 65.19 (4%)
> - crf 21 VMAF 73.00 (20%)
> - crf 10 VMAF 75.38 (138%)

**File 1, new branch:**
`ab-av1 crf-search -e libx265 --pix-format yuv420p10le --min-vmaf 95 --vmaf pool=harmonic_mean --vmaf n_threads=16 -i .\00004.m2ts --preset 5`
> - crf 32 VMAF 82.77 (4%)
> - crf 21 VMAF 94.77 (21%)
> - crf 10 VMAF 98.17 (145%)
> crf 20 VMAF 95.26 predicted full encode size 6.64 GiB (25%) taking 2 hours
--------------------------------------------------------------------------------------------------
`ab-av1 crf-search -e libx265 --pix-format yuv420p10le --min-vmaf 95 --vmaf pool=harmonic_mean --vmaf n_threads=16 -i .\00004.mkv --preset 5`
> - crf 32 VMAF 82.62 (4%)
> - crf 21 VMAF 94.73 (20%)
> - crf 10 VMAF 98.16 (144%)
> crf 20 VMAF 95.22 predicted full encode size 6.00 GiB (25%) taking 2 hours

Both containers have almost matching vmaf results as expected.

**File 2, old branch:**
`ab-av1 crf-search -e libx265 --pix-format yuv420p10le --min-vmaf 90 --vmaf pool=harmonic_mean --vmaf n_threads=16 -i .\00163.m2ts --preset 5`
> - crf 32 VMAF 49.53 (3%)
> - crf 21 VMAF 52.84 (17%)
> - crf 10 VMAF 53.22 (116%)
--------------------------------------------------------------------------------------------------
`ab-av1 crf-search -e libx265 --pix-format yuv420p10le --min-vmaf 90 --vmaf pool=harmonic_mean --vmaf n_threads=16 -i .\00163.mkv --preset 5`
> - crf 32 VMAF 83.03 (3%)
> - crf 21 VMAF 95.28 (18%)
> - crf 26 VMAF 91.73 (7%)
> crf 27 VMAF 90.69 predicted full encode size 1.73 GiB (6%) taking 78 minutes

**File 2, new branch:**
`ab-av1 crf-search -e libx265 --pix-format yuv420p10le --min-vmaf 95 --vmaf pool=harmonic_mean --vmaf n_threads=16 -i .\00163.m2ts --preset 5`
> - crf 32 VMAF 83.06 (3%)
> - crf 21 VMAF 95.24 (18%)
> - crf 22 VMAF 94.71 (15%)
> crf 21 VMAF 95.24 predicted full encode size 5.26 GiB (18%) taking 2 hours
--------------------------------------------------------------------------------------------------
`ab-av1 crf-search -e libx265 --pix-format yuv420p10le --min-vmaf 95 --vmaf pool=harmonic_mean --vmaf n_threads=16 -i .\00163.mkv --preset 5`
> - crf 32 VMAF 83.03 (3%)
> - crf 21 VMAF 95.28 (18%)
> - crf 22 VMAF 94.74 (15%)
> crf 21 VMAF 95.28 predicted full encode size 4.85 GiB (18%) taking 2 hours

Again, results are as expected, they match between containers in the new branch, and they also match the mkv results of the old branch, as they should.  So I would consider this issue fixed.

The weird part is that the corrupted frames with the artifacts are still happening in the encoded samples (not in the lossless samples, those are fine) and I found out that it also happens with the av1 encoded ivf sample files. So I guess that was not the reason why it was failing, as they don't seem to affect the scores whatsoever, but there must have been something else wrong that has been fixed by using mkv for the lossless samples. 

It should also mean that those artifacts were not because of the container, but maybe because of the source video codec (vc-1)? I don't know. But I know it does not happen when the m2ts is changed into mkv thorugh MKVToolNix, it must have been cleaning the video metadata or something, no idea, but it works and avoids the appearance of those artifacts when the sample gets encoded.

**Comment by alexheretic** [comment]
Thanks for testing!

Perhaps the corruption is a playback error and when the videos are converted into yuv streams for VMAF there is no corruption. I would expect bad vmaf scores otherwise.

Anyway iiuc i think we can close this once the pr is merged.
